### ISSUE TITLE
New sites are not initialized as HTTPS

### ISSUE THREAD

**Issue by chriszarate** [mlaa/commons#10]
When a user creates a new site, the SITEURL and HOME options are not set to HTTPS. This isn't a big problem but can lead to mixed content warnings. It's a longstanding bug in WP core:

https://core.trac.wordpress.org/ticket/14867

**Comment by chriszarate** [comment]
Looks like this will be fixed in WP 4.4!

**Comment by modelm** [comment]
Tested this today and it is still a problem on the current Commons, using WP 4.4.2.

**Comment by modelm** [comment]
tracked in trello, so closing this.
