### ISSUE TITLE
Theme requests

### ISSUE THREAD

**Issue by chriszarate** [mlaa/commons#15]
[Radcliffe](https://wordpress.org/themes/radcliffe/)
[Shaken Grid Free](http://shakenandstirredweb.com/theme/shaken-grid-free)
[Arcade](https://wordpress.org/themes/arcade-basic/)
[Sparkling](http://colorlib.com/sparkling/)
[Maskitto Light](https://wordpress.org/themes/maskitto-light/)

Requested themes will be vetted for quality and maintainability.

Feel free to add to this ticket at any time.

**Comment by kshkim** [comment]
Commons book development is picking up. When would these requested themes be available for members? Thank you @chriszarate!

**Comment by chriszarate** [comment]
I've reviewed and installed all of these except Shaken Grid Free. If you want this theme, I suggest purchasing the full version (but let's talk about it first).

The themes are not network activated yet, so you'll need a super admin to activate them manually on the sites you want to use them on.

This ticket can stay open for future requests.

**Comment by chriszarate** [comment]
Closing; moving theme/plugin requests to wiki.
