### ISSUE TITLE
resize images in slider

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/commons#20]
So that they're all the same size, and so the slider doesn't resize itself all the time. @terrainsvagues, do you want to tackle this one?

**Comment by terrainsvagues** [comment]
Yessir

**Comment by terrainsvagues** [comment]
These are all done except for the video, which is going to require some CSS for resizing, since I can't use an embed code in the slider. 
Here's some info on the kind of code that might be useful: http://presscustomizr.com/snippet/embedding-a-youtube-or-vimeo-video-in-your-slider/

**Comment by chriszarate** [comment]
This is done. The video in question is gone.
