### ISSUE TITLE
As a member, I cannot leave a group

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/commons#28]
Story: I am a member in two different groups. After leaving them, I get a confirmation saying I've successfully left but when I log back in they still appear under "my groups". 

User's comments: James Hatch tried to leave two different groups, LLC Late 18th Century English and LLC English Romantic. He received a message saying he had successfully left the group. The next time he visited the Commons, he was back in the group. I asked him to replicate on both groups today: he got the message saying he had successfully left and, once again, he logged out and logged back in again, and lo! He was back in both groups.

**Comment by modelm** [comment]
The cause is being the primary member in those forums. We should make it obvious that leaving a primary forum isn't supported - something like a badge indicating "primary membership" next to the group name for the current user.

**Comment by modelm** [comment]
https://github.com/mlaa/hc-notifications/commit/92bdec8aa56e520539d8ba9927cfd4adc0eed62e
