### ISSUE TITLE
On zoomed-in Chrome screen, grey-transparent caption takes up too much of slider image 

### ISSUE THREAD

**Issue by ALGibson** [mlaa/commons#29]
[CA slider.pdf](https://github.com/mlaa/commons/files/86478/CA.slider.pdf)

Story: On my (giantified) screen, the gray-transparent caption on slider image on the Commons landing page take up 3/4 of a given slide. In the case of the Connected Academics slide, for example, this means it is hard to click in order to get to the featured site (I have to find the small sliver of white outside caption and click there to get to the featured site). I am using Chrome browser.

Replicate: Not able to replicate... may be specific to user's browser/screen settings

**Comment by chriszarate** [comment]
Closing as issue is an edge case that should be mitigated in `levitin`.
