### ISSUE TITLE
change "blogs" to "sites" wherever possible in translations

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/commons#3]
See mlaa/cbox-mla#57

**Comment by JonathanReeve** [comment]
Reopening, because as @terrainsvagues noticed, there are still a few places where we see the word "blog" or "blogs" around, which is inconsistent with our current use of "sites."

**Comment by terrainsvagues** [comment]
1. When on a group's page, the left hand menu says "blog" if there is an associated site.
2. When setting up or managing a group, the column header is "group blog" and all references are to blogs, not sites.
![screen shot 2015-02-25 at 9 53 34 am](https://cloud.githubusercontent.com/assets/7083891/6372738/35fddaa2-bcd4-11e4-8c42-c691a4215d46.png)

**Comment by kfitz** [comment]
One spot for a quick change: the Big Orange Block on the front page that reads "MLA Blogs." (Eep.)

**Comment by terrainsvagues** [comment]
![Image](https://cloud.githubusercontent.com/assets/7083891/6604295/d430c778-c7fd-11e4-9e69-c1b9a3ca066a.png "Here is another example")

**Comment by JonathanReeve** [comment]
This one is going to be kind of tricky, since it turns out bp-groupblog isn't translatable without altering the plugin itself. I've submitted a bug report for this upstream, at boonebgorges/bp-groupblog#41. Will probably write a hack of some sort to force-enable translations for bp-groupblog.

**Comment by JonathanReeve** [comment]
This one was disproportionately difficult for its apparent simplicity. With the exception of the homepage widget (see rollout plan in f0181dc), this should be fixed. Feel free to reopen if this emerges somewhere again.
