### ISSUE TITLE
Include user sites in ElasticSearch results

### ISSUE THREAD

**Issue by mikethicke** [mlaa/commons#392]
Currently results from user sites are not returned when searching. This would be desirable functionality, especially for HASTAC. Investigate adding a sites facet to ElasticSearch and implement if feasible.

**Comment by mikethicke** [comment]
The following commits add search for user sites:

- https://github.com/MESH-Research/hc-custom/commit/4ab3ecf2d231b05e02f3a0b83a292961be6dab50 (Add posts and pages to search)
- https://github.com/MESH-Research/boss-child/commit/64329be4d35244c5807606e7dd05ee0e3e6999f7 (Don't show post thumbnails in search results)
- https://github.com/MESH-Research/elasticpress-buddypress/commit/2c5dd12ca313e5b51ba25ce9a310b92da2f885e4 (Include user sites in search results)

A user site can be added to the search by activating the ElasticPress plugin on that site and running ```wp elasticpress index --setup --yes --url={site url}``` once. Subsequent updates to the site should be indexed automatically by the ElasticPress plugin.

When a network facet is selected in search (eg. HASTAC, MLA, etc), then any indexed user sites will also be searched.

Additionally, post content is now being search (previously only titles and some custom fields were searched).

**Comment by bjr70** [comment]
Another observation. It looks like on the home page you can hit the enter button to do the search, but once you've done a search that no longer works. It does look like the search is redone when you're on a results page but this could be confusing for users.

**Comment by bjr70** [comment]
Overall the search does work. The navigation issues aside, the search results appear to update properly over multiple searches. I suggest adding the blog title to the search results so people know where the post is from, but other than that I think it's good.

**Comment by mikethicke** [comment]
Add blog name to search results for pages and posts: https://github.com/MESH-Research/boss-child/commit/fe19370551f91ee876bcaafe2d77616487c3220b

**Comment by kfitz** [comment]
Yeah, I think the searches are working, but the URLs don't update. I searched for "politics," and got a results page at https://hastac.hcommons-staging.org/?s=politics. I then followed a link, used the back button, and replaced "politics" in the search bar with "commercial." It took a few seconds for the results page to update, but the URL remained the same. Followed a link and searched the page for "politics" to see if I was now looking at a subset of the first search, but there was no reference to "politics" on that page. Used the back button and landed on https://hastac.hcommons-staging.org/?s=politics, with the first set of search results.

**Comment by mikethicke** [comment]
Yeah---I believe that's how it has always been. Changing that behavior isn't super easy and it might make sense to just prioritize a full redesign / rewrite of search.

**Comment by babaklar** [comment]
Same as Bonnie and Kathleen--searches are working but URL links aren't updating. I also noticed I am having trouble finding profiles amongst the search results. For example, when I try searching for "Mike Thicke" and "Bonnie Russell" profile, the only results that show up are posts. When I use the filters to narrow my search only to members, I'm not getting any results.

**Comment by mikethicke** [comment]
You need to make sure the network facets are set correctly:

![Screen Shot 2022-07-01 at 11.51.40 AM.png](https://images.zenhubusercontent.com/6108aeed64d7503f6ae51eff/8f69dfaf-c49b-4a22-bbb5-b9edd9ed768c)
