### ISSUE TITLE
Mastodon handle on HC profiles

### ISSUE THREAD

**Issue by kfitz** [mlaa/commons#496]
Currently HC profiles have a field in which a user can add a Twitter handle. It would be great to have a similar field for Mastodon handles.

![Screenshot 2022-11-16 at 1.05.32 PM.png](https://images.zenhubusercontent.com/61099b51dc6752f2a2b6fea3/c0871561-72fb-4cef-8323-1bb7cd6ce17a)

![Screenshot 2022-11-16 at 1.06.22 PM.png](https://images.zenhubusercontent.com/61099b51dc6752f2a2b6fea3/f09bb2ec-74f9-4111-b58b-b092b4487e32)

**Comment by mikethicke** [comment]
https://github.com/MESH-Research/hc-member-profiles/commit/0cd8f0b337a9194809b9850549fc531c131c5394 add support for Mastodon handles on HC profiles.

Handles can be in the form @username@server.social or username@server.social.

The ```rel="me"``` attribute is added automatically. It is also added to other profile links where appropriate (Twitter, ORCID, etc). It is not added to websites, as those are not necessarily personal. This should remove the need for MESH-Research/hc-admin-docs-support#382 .
