### ISSUE TITLE
Implement ORCID as a login method

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#497]
Work to implement ORCID as a login method.

**Comment by bjr70** [comment]
I was able to add ORCID as a login method on dev on my own account with no issue at all. 

When I went to log into comanage as me when logged in with ORCID I got this error The identifier "0000-0002-0374-0384@orcid-gateway.hcommons-dev.org" is not registered. If your request for enrollment is still being processed, you will not be able to login until it is approved. Please contact an administrator for assistance."

My petition for the ORCID login method is here: https://registry.hcommons-dev.org/registry/co_petitions/view/389782

I was able to register as Ferdinand Test and use ORCID as my login method and it worked perfectly. https://registry.hcommons-dev.org/registry/co_people/canvas/128654

**Comment by babaklar** [comment]
I was able to register as Dave Test and use ORCID as the login method. No problems: [https://registry.hcommons-dev.org/registry/co_people/canvas/128659](https://registry.hcommons-dev.org/registry/co_people/canvas/128659)

**Comment by mikethicke** [comment]
Implementation is complete, tested on production. Will be made available to users once communication is sent out.
