### ISSUE TITLE
Add updated HASTAC logo to top nav bar in HASTAC Commons

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#498]
HASTAC emailed us with a higher resolution logo they'd like added to the top nav bar in HASTAC Commons. File is attached.[https://app.zenhub.com/files/19561322/87a9e0e3-1617-46cc-8c0a-5623b643af4e/download](https://app.zenhub.com/files/19561322/87a9e0e3-1617-46cc-8c0a-5623b643af4e/download)

**Comment by zwhnz** [comment]
@mikethicke giving this a little boost - Larissa has updated the attached file after conversation with HASTAC and I'd like to be able to go back to them by the end of this sprint if I can. Thanks!

**Comment by mikethicke** [comment]
Logo is updated.

**Comment by zwhnz** [comment]
Thanks @mikethicke !
