### ISSUE TITLE
Resolve orcid-gateway.hcomons.org to correct load IP

### ISSUE THREAD

**Issue by mikethicke** [mlaa/commons#500]
Looks like the name orcid-gateway.hcommons.org does not resolve to the same load balancer as the other IDPs, I don't have access to fix that. Someone with AWS credentials will need to address it. The name orcid-gateway.hcommons.org resolves to a non-existent site on hcommons.org

BAD

nslookup orcid-gateway.hcommons.org
Server:        8.8.8.8
Address:    8.8.8.8#53

Non-authoritative answer:
Name:    orcid-gateway.hcommons.org
Address: 18.213.19.113
Name:    orcid-gateway.hcommons.org
Address: 52.203.187.67

GOOD

nslookup mla-idp.hcommons.org
Server:        8.8.8.8
Address:    8.8.8.8#53

Non-authoritative answer:
Name:    mla-idp.hcommons.org
Address: 34.204.228.19
Name:    mla-idp.hcommons.org
Address: 54.174.222.185

**Comment by ericknappe** [comment]
We are looking for Rules on a :443 listener in the Load Balancers section of EC2.

The correct listener will have rule entries for hc-idp,hcommons.org, mla-idp.hcommons.org, google-gateway.hcommons.org, etc.

I suspect that there is no entry in the Prod ALB for orcid-gateway.hcommons.org

**Comment by mikethicke** [comment]
I think this should be good to go.

Non-authoritative answer:
Name:	orcid-gateway.hcommons.org
Address: 34.204.228.19
Name:	orcid-gateway.hcommons.org
Address: 54.174.222.185
