### ISSUE TITLE
HCID password reset broken on staging

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#508]
**Describe the bug**
Test user receives error when trying to reset HC password on hcommons-staging. Error: PWM 5036 "There is no contact information available for your account. Please contact your administrator." This does work on production. 

**To Reproduce**
1. Register test user with HCID or user test user with HCID
2. Click on '....'Click on Login, then the HCID logo, then click "Forgot Password" below the password field.
3. Search by user ID. 

**Expected behavior**
The user should be able to search by user ID and then get sent to a page to enter the code that was sent to their email. This does work on production, but is broken on staging. 

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [x] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by babaklar** [comment]
I had a slightly different version of this bug. When I tested the password reset button, I didn't receive an error message but was sent to the home screen for hcommons-staging.org. I used Walter Test (hctester70).

**Comment by mikethicke** [comment]
PwmConfiguration.xml had the old mlacommons URL still as it's self IP, and so the password reset link was going to the wrong place. This appears to be working now.
