### ISSUE TITLE
Invitations to hidden groups cannot be accepted

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#509]
**Describe the bug**
When a user is invited to a hidden group they receive an invitation. They must open the invitation and accept it before being allowed in. The invitations are sent, but when you click on them to view and accept they return you to the home page.

**To Reproduce**
1. Log in as hctester50
2. Click on the notification "You have an invitation to the group: MESH"
3. The site returns you to the homepage
4. Larissa was also able to replicate this with hctester50
5. It is working on production

**Expected behavior**
The user should be able to open the invitation and see buttons to accept the invitation. 

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [x] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by mikethicke** [comment]
Confirmed.

**Comment by mikethicke** [comment]
Addressed by 10373995eee256e2af457c19a98abf69ca9a65dc
