### ISSUE TITLE
hctester40 and hctester50 did not receive automatic MLA committee assignments

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#510]
**Describe the bug**
Test users should have received automatic membership in MLA committees: Dave did not receive his membership to https://mla.hcommons-staging.org/groups/committee-on-the-literatures-of-people-of-color-in-the-united-states-and-canada/. It is listed in his COmanage profile https://registry.hcommons-dev.org/registry/co_people/canvas/128718.

**To Reproduce**
1. Register with a test user that has an automatic committee assignment
2. Go to groups and click on "My Groups"
3. Check to see that the group is listed. 

**Expected behavior**
The user should have automatic membership in any groups managed in comanage and listed on their comanage profile. 

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [x] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by babaklar** [comment]
Ferdinand Test's (hctester40) UP committee memberships worked. His MLA committee--Committee on Disability Issues in the Profession (M037)--did not.

**Comment by bjr70** [comment]
Note: It looks like Dave Test is not a member of that MLA group on production, but is on staging/dev.

**Comment by mikethicke** [comment]
MLA group membership is screwy. There's a separate plugin that live queries the MLA's membership API and removes users from memberships if they aren't there. If managed groups work for other societies then I think we're good. We probably shouldn't even test MLA group membership on dev.

**Comment by bjr70** [comment]
We'll need to keep an eye on it in production, but I am reasonably OK with that solution. Closing.
