### ISSUE TITLE
Group creation throws error when creating a discussion board

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#511]
**Describe the bug**
Tried creating "Dave's Group 2023" using hctester50. Was able to create the group blog, but it gave an error when trying to create the discussion: "There has been a critical error on this website."

The group was created, and when trying to add the discussion board from the front-end settings the same error occurs. 

https://hcommons-staging.org/groups/daves-group-2023/

The group shows up in the groups list but has no join button. It was created as a public group, but could not get past the create a discussion step.

**To Reproduce**
1. Log into staging as hctester50
2. Go to Dave's Group 2023
3. Click on Manage/Discussion and try to enable it.

**Expected behavior**
The discussion should be set up and you should move to the next screen in creation, or be taken back to the settings with a confirmation that the discussion has been added. 

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [x] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by babaklar** [comment]
Received the same error while going through the process of creating a group as Ferdinand (hctester40). After clicking "next step" on the Group Discussion question, I received the "There has been a critical error on this website" message. Encountered the same error when attempting to turn it on through the group settings as well.

**Comment by babaklar** [comment]
Adding another update on this. In the group I created I haven't been able to get the discussion to work, but when I go to the "discussion" tab, it's showing the discussion board is for a private group called "(Formerly Woodrow Wilson) Career Enhancement Fellowship, 2020-21." The test post I created isn't showing on the page, but is showing in the activity feed. 
![Screen Shot 2023-01-04 at 11.56.05 AM.png](https://images.zenhubusercontent.com/62572e0e3e1b973699e0382a/c574fd61-3415-4de8-be07-e84daa8a0f21)![Screen Shot 2023-01-04 at 12.01.04 PM.png](https://images.zenhubusercontent.com/62572e0e3e1b973699e0382a/34710524-c36e-4daa-b4ea-ff0199f77e2c)

**Comment by mikethicke** [comment]
I believe this is working now.

**Comment by bjr70** [comment]
Yes, this is working. Closing.
