### ISSUE TITLE
Email not working on the staging server

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#513]
**Describe the bug**
When joining a private or hidden group an email should be sent to the user to notify them that they've been invited. Those emails are not being sent. The reply-by-email functionality is also not working. 

**To Reproduce**
1. Log in as hctester50
2. Go to the group "Dave's Group 2023"
3. Note the email address for the group
4. Error returned: "Your message couldn't be delivered to group-daves-group-2023@reply.hcommons-staging.org because the remote server is misconfigured. See technical details below for more information."

**Expected behavior**
User should be able to create topics and reply-by-email and also receive emails when invited to groups. 

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [x] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by mikethicke** [comment]
I believe this should be working now.

**Comment by bjr70** [comment]
Email is working!!
