### ISSUE TITLE
Screen refreshes badly after the creation of a discussion topic

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#516]
**Describe the bug**
When creating a discussion topic the page refreshes badly. The topic does not appear in the activity feed. 

**To Reproduce**
1. Log in as hctester50
2. Submit a new discussion topic in this group https://hcommons-staging.org/groups/lets-try-that-again/
3. The screen looks like this:
![alljackedup.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/0f2f6764-6071-4a73-b2a3-b84d64e5fe28)

**Expected behavior**
The screen should have the title of the group at the top. 

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [x] Tested on production
- [x] Occurs on productions

**Screenshots**

**Additional context**

**Comment by bjr70** [comment]
This is also happening on production.

**Comment by bjr70** [comment]
Hmmm sometimes shows in activity feed and sometimes doesn't. Not consistent.

**Comment by mikethicke** [comment]
Confirmed. I suspect a ```<div>``` tag isn't being closed correctly from an ajax request.

**Comment by mikethicke** [comment]
I spent a long time trying to diagnose this today. It seems to be the result of scrolling to a specific part of the page using an #anchor in the URL after posting a new discussion.

1) Submit a new discussion---the page renders correctly.
2) After the page is fully rendered, the page scrolls to the #post-##### anchor. It is now broken.
3) Remove #post-##### from the URL and hit enter to reload the page. It renders correctly.
4) Put #post-##### back in the URL bar and hit enter. It is now broken.

This behavior happens even if javascript is turned off. You can unbreak the page just by using the element browser in dev tools to scroll to a specific part of the header.

The issue reproduces in Chrome, Safari, and Firefox (on Mac).

There must be something weird in the page structure / styling that is causing rendering to break when it scrolls to a specific part of the page, but I can't see what it is.

As this is a visual bug (doesn't effect functionality) and occurs on production so isn't specific to the WP update, I am going to close.
