### ISSUE TITLE
Update ARLIS/NA registration page to remove AJS text

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#519]
On the ARLIS/NA registration page, the email field is labelled with "Use the email address associated with your AJS member record." This needs to be updated to "Use the email address associated with your ARLIS/NA member record."
![Screen Shot 2023-01-06 at 2.43.28 PM.png](https://images.zenhubusercontent.com/62572e0e3e1b973699e0382a/031082c9-73ba-426a-9ae8-335c37c90dc4)

**Comment by babaklar** [comment]
Updated.

**Comment by mikethicke** [comment]
This can be changed in Enrollment Flows | {Edit Enrollment Flow } | Edit Enrollment Attributes | Edit {the incorrect filed}
