### ISSUE TITLE
Academic Interests: Slow to Load and Cursor Issues

### ISSUE THREAD

**Issue by stephanievaskomsu** [mlaa/commons#520]
**Describe the bug**
Sometimes it works slowly and sometimes I'm typing words but not getting suggestions on the profile page, it just says searching and enter 1 letter, cursor is in a weird place after first is entered. Once I get one in, the widget works!

**To Reproduce**
1. Go to the academic interests piece on profiles
2. Start to enter interests

**Expected behaviors**
I expect the list to populate once I start typing a letter and that the cursor is directly to the right of the suggestions.

**Context**
Does this bug on production, development, or both?
- [X] Tested on development instance
- [ ] Occurs on development instance
- [ ] Tested on production
- [ ] Occurs on productions

**Screenshots**
Added cursor screenshot. [Screen Shot 2023-01-06 at 10.50.20 AM.png](https://images.zenhubusercontent.com/61eefe7748f5546f51ec4d3b/7463ed08-9df0-45b6-90b2-5abc9e51febb)

**Additional context**

**Comment by mikethicke** [comment]
Slowness I can't do much about right now. This input relies on the select2 jquery library for tokenizing inputs. It's a bit hackish and hard to style well.

https://github.com/MESH-Research/boss-child/commit/500ecfc58040cad24b23051c0fbba1f9a3399c25 Adjusts the input container height and removes margin / padding to make the input cursor line up better with the tokenized inputs. It is not a perfect solution, especially when an input wraps lines. But it seems better than the current situation.

**Comment by bjr70** [comment]
Reopening for @ericknappe to look at some of the backend caching originally created for this code. There may be a process that is not running.

**Comment by rekmla** [comment]
The plugin mla-academic-interests has a rest controller that queries terms and returns them to the select2 javascript on the front end. The plugin bin directory contains a php script to prime the cache with all the academic interest terms to speed up the edit profile interest picker. I've tested HC in it's current state, after flushing cache and after priming cache and I get the same 4-5 second response in every case entering a word. The response can be quicker when going letter by letter. I'll need to check again when there is some load on the system.

**Comment by bjr70** [comment]
We're going to close this issue and reopen one specifically in the context of art and art history.
