### ISSUE TITLE
Reply by email not working in staging groups

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#522]
**Describe the bug**
Both reply and post by email don't seem to be working on groups for hcommons-staging.org. Email is working correctly for notifications. Not sure if this could be connected with [this closed issue](https://app.zenhub.com/workspaces/hc-development-61143609f268f000196abf18/issues/gh/mesh-research/hc-admin-docs-support/277). The test group has the word "group" in the title, which was part of the issue last time. 

**To Reproduce**
1. Go to 'Ferdinand's Test Group'
2. Post on the discussion board
3. Receive email notification. When replying directly to the email, this message is received: Your message couldn't be delivered to 6dad4ae4f5546d9f4bbc0aa548931441c129846c5ec712a845f2f9cb832cabdabefa095de9b98fd5fdf19185d00d7591@reply.hcommons-staging.org because the remote server is misconfigured. See technical details below for more information.
4. When trying to reply in a new email, receive this message: 	
Your message couldn't be delivered to group-ferdinands-test-group@reply.hcommons-staging.org because the remote server is misconfigured. See technical details below for more information.

**Expected behavior**

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [ ] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by bjr70** [comment]
Tried to create a topic on the group "Dave's Party" and that also failed. Notifications are working, but create and reply to by email are not. 

Your message couldn't be delivered to group-daves-party@reply.hcommons-staging.org because the remote server is misconfigured. See technical details below for more information.

**Comment by babaklar** [comment]
Confirmed having "group" in the title was not the issue.

**Comment by mikethicke** [comment]
I believe this is a Sparkpost configuration issue not related to the WordPress updates.

To make post-by-email work, a Sparkpost webhook needs to be able to POST to hcommons-staging.org, but I believe AWS security groups are preventing this from working.

See: 
- https://github.com/r-a-y/bp-reply-by-email/wiki/SparkPost For setting up BP-RBE with Sparkpost
- https://support.sparkpost.com/docs/tech-resources/inbound-email-relay-webhook For Sparkpost documentation on Relay Webhooks
- https://support.sparkpost.com/docs/tech-resources/webhook-authentication/?b_id=7411 For Sparkpost documentation on security configuration

If this works on hcommons-dev, I'm not sure how it's been configured.
