### ISSUE TITLE
Image upload error on hcommons-2.dev

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#524]
When trying to upload a new banner to hcommons-2.dev, I am receiving the following error message: "The server cannot process the image. This can happen if the server is busy or does not have enough resources to complete the task. Uploading a smaller image may help. Suggested maximum size is 2560 pixels." The image is significantly below the pixel limit. 
![Screen Shot 2023-01-25 at 1.45.06 PM.png](https://images.zenhubusercontent.com/62572e0e3e1b973699e0382a/112a35d8-3917-46fd-9543-2ab6ce1139ad)

**Comment by mikethicke** [comment]
This appears to have been a disk space issue. It should be corrected.

**Comment by babaklar** [comment]
Tested and this seems fixed.
