### ISSUE TITLE
Switch from GA / Matomo Pilot

### ISSUE THREAD

**Issue by stephanievaskomsu** [mlaa/commons#542]
See business case/rationale here: https://docs.google.com/document/d/1ZFGNkzBImXGkmAifgXQwnVX8Cat_tB_877Fl4v-67UI/edit?usp=sharing

**Comment by tzouris** [comment]
https://matomo.org/installing-matomo-for-wordpress/

**Comment by bjr70** [comment]
Switch on April 23rd

**Comment by tzouris** [comment]
Signed up with hello@hcommons.org and activated the account. Free, 21-day trial begins today.

**Comment by tzouris** [comment]
Mike installed the WP plug-in on hcommons prod and we set it up. It looks like it's started collecting data. We'll come back to it tomorrow.

**Comment by tzouris** [comment]
Matomo is working. I created users (up to 3 allowed) for Stephanie and Zoe to try the view-only accounts, but we'll share the admin account too.

**Comment by tzouris** [comment]
We'll evaluate the tool and make a decision. Closing this ticket.
