### ISSUE TITLE
Unable to search by email address in CoManage

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#551]
**Describe the bug**
When searching my email address in CoManage on both dev and prod, "no results found." Users can do be found via their name.  

**To Reproduce**
1. Go to '[https://registry.hcommons-dev.org/registry/co_people/index/co:2](https://registry.hcommons-dev.org/registry/co_people/index/co:2)'
2. Click on 'Filter'
3. Search for an email address
4. See error: "no results found"

**Expected behavior**

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [x] Tested on production
- [x] Occurs on productions

**Screenshots**

**Additional context**

**Comment by bjr70** [comment]
Created PMO#1109 in SCG's ticketing system to request a fix.

**Comment by rekmla** [comment]
SCG noted that this has been fixed recently in [CO-2600](https://todos.internet2.edu/browse/CO-2600) and is now available in the comanage develop branch. That has been merged into a new branch in the HC comanage repo - develop-hc-031723 - and deployed to registry.comanage-dev.org. While the bug fix has been confirmed, this release still needs to be tested before being deployed to production.

**Comment by bjr70** [comment]
Fix rolled out. Closing.
