### ISSUE TITLE
Test COmanage elector data filter

### ISSUE THREAD

**Issue by mikethicke** [mlaa/commons#552]
## Background

In WordPress each user can have only one email address. In COmanage, they might have many email addresses. Currently, users with multiple email addresses  select which email to use in their Settings | General page in WordPress. We are moving that selection to a COmanage dashboard widget.

This introduces a concept of a "preferred" email address in COmanage. Users can have one email address designated as preferred, and that is the email that will be provisioned to LDAP and passed to WordPress. If the user has no preferred address, then COmanage will fall back to provisioning one of their "official" addresses.

The Email Address Elector Data Filter ( Configuration | Data Filters | Email Address Elector ) handles this functionality.

## To Do

- Activate the Email Address Elector on COmanage dev.
- Register a test user and confirm that their email address is being passed correctly to WordPress on login.
- Add a second email address through the dashboard widget and confirm that just one email address is being passed to WordPress on login.
- Select a different address as preferred, and confirm that it is now the address being passed to WordPress on login.

**Comment by bboggmsu** [comment]
Email Address Elector is active in Dev. 
Testing is still needed.  We will likely test on 03/24/23

**Comment by bjr70** [comment]
Registration works correctly when creating an HCID but comanage is forcing you to log in again after creating it and it should not. That should move to the countdown timer.

When this filter is activated when you go to log in after creating the HCID you get the following error: 

The identifier "Ferdinand99999@hcommons-test.mla.org" is not registered. If your request for enrollment is still being processed, you will not be able to login until it is approved. Please contact an administrator for assistance.

**Comment by mikethicke** [comment]
WordPress should be correctly be updating user emails when passed on login. If exactly one email address is passed on login and it doesn't match the current email, the user's email address will be updated accordingly.

Should now be able to test:

- Set a new email to 'preferred'
- Re-login
- See that user's email has been updated accordingly.

**Comment by mikethicke** [comment]
Re: re-authenticating. This is also the behavior on production for HCIDs (as soon as you enter a username and password for the HC option, you are required to authenticate).

**Comment by bjr70** [comment]
Closed per conversation with devs.
