### ISSUE TITLE
1 Week reminder email

### ISSUE THREAD

**Issue by stephanievaskomsu** [mlaa/commons#556]
- [x] SEV drafts reminder email
https://docs.google.com/document/d/1St5fQxXxet2YI6KGNh1jb34HxeIhQNFLfM0p5kAb81w/edit?usp=sharing

- [x] LB puts email in Stripo template

- [ ] MT sends email on 3/27 @ 11AM eastern

**Comment by babaklar** [comment]
Zipped file is attached here.[https://app.zenhub.com/files/19561322/d3c00f01-cbfe-4a2f-95e4-8fa6cf0be91b/download](https://app.zenhub.com/files/19561322/d3c00f01-cbfe-4a2f-95e4-8fa6cf0be91b/download)

**Comment by mikethicke** [comment]
Sent.
