### ISSUE TITLE
Create a site no longer working - button to progress is missing 

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#557]
**Describe the bug**
When creating a site The first step appears but the page ends at the "This is a course site" line. 

**To Reproduce**
1. Click on Create a Site
2. Scroll down
3. No button to progress

**Expected behavior**
You should see a "next" button to progress to the next step. 

**Context**
Does this bug on production, development, or both?
- [ ] Tested on development instance
- [ ] Occurs on development instance
- [x] Tested on production
- [x] Occurs on productions

**Screenshots**

**Additional context**

**Comment by mikethicke** [comment]
Messed up committing changes for MESH-Research/commons#460
