### ISSUE TITLE
LAST Survey Reminder

### ISSUE THREAD

**Issue by stephanievaskomsu** [mlaa/commons#561]
- [ ] SEV drafts email
https://docs.google.com/document/d/1PigAJ7IA46HjHLL78SYIu24t__VMJbxelIsqCAk8kGI/edit?usp=sharing

- [x] LB formats email in Stripo

- [x] MT sends out email, Monday, 4/3, between 9-11 AM

**Comment by babaklar** [comment]
Email template updated here:[https://app.zenhub.com/files/19561322/8ee438b8-e9e4-4807-b7b7-9a63e44bfe02/download](https://app.zenhub.com/files/19561322/8ee438b8-e9e4-4807-b7b7-9a63e44bfe02/download)

**Comment by mikethicke** [comment]
Survey reminder sent.
