### ISSUE TITLE
Create a Site link is missing on the sites page

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#572]
Disappeared yesterday afternoon as far as we can tell. This is happening more often, is there something specific causing this?

**Comment by mikethicke** [comment]
Traced to a caching error for the buddypress 'root_blog_options' key. (bp-core-options.php::bp_core_get_root_options()). Flushing cache corrected the issue. I couldn't find what caused the original error.

**Comment by mikethicke** [comment]
https://github.com/MESH-Research/hc-custom/commit/9db795eaac544c5a71ec6b640f4db0171191fc6e Attempts to force blog creation to always be enabled. Hoping this solves the issue permenantly.
