### ISSUE TITLE
Finalise MailChimp sync

### ISSUE THREAD

**Issue by zwhnz** [mlaa/commons#617]
**Initial Import into MC**
- Import all users who last session was within the past 3 years EXCLUDING all HASTAC users who have not logged in (i.e. do not have a session date more recent than the date of import)
- Include all society memberships as tags in MailChimp
- All should be imported into [commons-active audience](https://us9.admin.mailchimp.com/audience/)

**Ongoing**
- New users should be added to commons-active audience 
- Existing users who do not meet the criteria for import but who initiate a new session should be added to the commons-active audience
- Note: this sync can happen at an agreed upon interval (daily, weekly, etc.)

**To discuss**
- What interval do we want for the ongoing data sync?
- Need to check how many contacts would be created by the initial import criteria - we have to be mindful of costs so if it's outrageously high, we will need to adjust
- How can we conduct regular maintenance to prevent accumulating dead weight of users who flip into inactive?
- Can we also tag users in our database with an active/inactive (or otherwise distinguish them) so we can export the full list when we need it? I guess we can just use the session data otherwise?

**Comment by mikethicke** [comment]
Working script: https://github.com/MESH-Research/dev-scripts/commit/aecf8dd2cde4cd406a9a6c78a4791035ee881b3b

Waiting on community for final configuration options.

**Comment by mikethicke** [comment]
Cron job scheduled for each Sunday at midnight.
