### ISSUE TITLE
HASTAC admin no longer able to add group members

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#618]
[One of the group admins](https://hastac.hcommons.org/members/jcahill/) for the [HASTAC Scholars group](https://hastac.hcommons.org/groups/hastac-scholars/) is experiencing an issue where she is no longer an admin for the group. Based on looking into this further, this may have accidentally been turned into a managed group, which could lead to the issues this user reported, although it's not clear whether this was supposed to be a managed group.  

"A user will request to join, I will accept the request, and then it immediately kicks them out of the group after a few seconds. I've been able to work around this when it happens by adding users manually, but that did not work this time - and now it kicked me out of the group too, unfortunately. I can still view the group contents and such though..."

**Comment by bjr70** [comment]
Issue resolved.
