### ISSUE TITLE
Remove plugins on Local dev for testing

### ISSUE THREAD

**Issue by mikethicke** [mlaa/commons#632]
Remove the following plugins (in Composer) and confirm they are uninstalled when rebuilding:

- [ ] tinymce-advanced
- [ ] avatar-privacy
- [ ] black-studio-tinymce-widget
- [ ] buddymeet
- [ ] classic-editor
- [ ] classic-widgets
- [ ] dynamicconditions
- [ ] ele-custom-skin
- [ ] email-posts-to-subscribers
- [ ] embed-any-document
- [ ] embed-pdf-viewer
- [ ] essential-addons-for-elementor-lite
- [ ] ewww-image-optimizer
- [ ] external-group-blogs
- [ ] events-manager
- [ ] force-regenerate-thumbnails
- [ ] google-document-embedder
- [ ] google-drive-embedder
- [ ] mailpoet
- [ ] memory-usage-bar
- [ ] multisite-custom-css
- [ ] network-plugin-auditor
- [ ] siteorigin-panels
- [ ] pdfjs-viewer-shortcode
- [ ] polylang
- [ ] public-post-preview
- [ ] remove-dashboard-access-for-non-admins
- [ ] shibboleth
- [ ] simply-show-ids
- [ ] so-css
- [ ] so-widgets-bundle
- [ ] sketchfab-oembed
- [ ] tablepress
- [ ] user-switching
- [ ] video-conferencing-with-zoom-api
- [ ] wordpress-mu-domain-mapping
- [ ] wpdatatables
- [ ] wpfront-notification-bar
- [ ] wp-to-twitter
- [ ] duplicate-post

**Comment by WebGardenGeek** [comment]
FYI, cannot remove so-widgets-bundle
