### ISSUE TITLE
Registered on hcommons-staging and ended up with an account on hcommons-dev

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#641]
**Describe the bug**
I registered as Ferdinand Test (hctester40) on mla.hcommons-staging but ended up with an account on hcommons-dev. 

**To Reproduce**
1. Register on hcommons-staging
2. Click on the email verification link and set up your login method
3. When you complete the process you end up in hcommons-dev

**Expected behavior**
The account should have been created on hcommons-staging. The video shows the bug in action.

https://images.zenhubusercontent.com/19561322/286776f1-327e-4965-9127-0cd77abf14a7/wp6_2_registration.mp4

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [ ] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by bjr70** [comment]
When I register on HC it's fine, but when I register on mla.hcommons-staging.org I end up getting an account on hc-dev. This may be org related. I'll try again with AUPresses, but this is looking like an org thing.

**Comment by bjr70** [comment]
@mikethicke this is an org issue. Same thing happens on up.hcommons-staging.org. Not sure of the implications on prod.

**Comment by bjr70** [comment]
When linking an ORCID ID after registration it creates the ORCID organizational ID in registry but dumps you out on dev and does not show up on staging in the settings area. There's got to be some sort of config issue here in the enrollments.

https://registry.hcommons-dev.org/registry/org_identities/view/112325
![loginmethods.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/1be18975-cb24-42de-bd53-9e00acdd288f)

**Comment by bjr70** [comment]
@mikethicke Something funky is going on on HC as well. I joined hc-staging with the username FerdinandTest. What ended up on hc-staging is a profile with the username ftest: https://hcommons-staging.org/members/ftest/. Somehow FerdinandTest was created on hc-dev. 

Ferdinand test registered on Jun 13, 2023 @ 0:11

FTest is showing  Jun 13, 2023 @ 0:07 

I cleared all cookies and cache before re-registering this user. We may need to pull logs.

**Comment by bjr70** [comment]
Enrollments are now behaving strangely. When enrolling on hcommons it's skipping the username step. See video. First enrollments is in Chrome after clearing cookies and cache. The second is in Firefox with all cookies and cache deleted and hasn't been used in some time (though current).

https://youtu.be/Tqg_6N4eH5Y

**Comment by mikethicke** [comment]
It appears that when we created staging we didn't create separate enrollment flows for most organizations. Will have to create staging-specific flows.

**Comment by bjr70** [comment]
Closing. Team has decided to use workarounds for now and not create those specific workflows. Staging will move to using the production IDMS in the coming months.
