### ISSUE TITLE
Member of MLA is immediately kicked out of public groups when joining them. 

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#643]
**Describe the bug**
Ferdinand Test is a member of MLA. When trying to join any public group it immediately pops up with "you have left the group" and kicks you out. 

**To Reproduce**
1. Log in as Ferdinand Test (google)
2. Go to https://mla.hcommons-staging.org/groups/2020-mla-convention/
3. Click join group
4. It immediately pops up with "you have successfully left the group" after joining and the join group button appears
![leftthegroup.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/e57de4ea-0bd1-4972-b80b-edd0bec28336)
5. If you look at the user's profile it shows they joined the group multiple times
![groupissue.png](https://images.zenhubusercontent.com/6109a91f4a7e4690a281a771/02e0acf2-6bb7-4696-93d5-980c41b03130)
6. User cannot post to group.
7. User can join groups on Humanities Commons, but not on MLA Commons.

**Expected behavior**
User should be able to join the group and post to it. 

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [ ] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by bjr70** [comment]
This appears to be on MLA Commons only. User can join groups on Humanities Commons and AUPresses with no issue.

**Comment by bjr70** [comment]
The user's flags appear to be correct: https://hcommons-staging.org/wp-admin/users.php?page=bp-profile-edit&user_id=1049878&wp_http_referer=%2Fwp-admin%2Fnetwork%2Fusers.php%3Fs%3Dhctester40

**Comment by mikethicke** [comment]
I suspect this is a cbox-auth issue (ie. an issue with MLA's API not having Ferdinand). Maybe they updated their database and didn't include our test users. We're phasing out cbox-auth anyways, so I'm going to turn it off on dev.

**Comment by mikethicke** [comment]
That did not address the issue. Working on a fix.

**Comment by mikethicke** [comment]
https://github.com/MESH-Research/hc-custom/commit/857c98bd17651cf05cc457f4eddaf660ee799fe7 removes the Join Group button for managed groups.

This behavior seems to have been caused by a group being both public and managed. It was public so it had a join button, but managed so the user was immediately removed.

**Comment by bjr70** [comment]
This is fixed. Closing.
