### ISSUE TITLE
Events functionality is not working in groups or from settings

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#649]
**Describe the bug**
There is no button to add a new calendar event in any group on UP, MLA, or ASEEES Commons, whether admin or member (settings are set to allow any member to create one). When clicking on "new event" from settings it just loads the profile page. 

**To Reproduce**
1. When I log in as hctester0 and go to https://hcommons-staging.org/groups/joes-june-surprise/events/ the new event button appears.
2. When I log in as hctester40 and go to https://up.hcommons-staging.org/groups/ferdinands-june-special-group/ the button does not appear. 
3. When I click on "new event" from settings on UP commons the same thing happens. It works on HC.

**Expected behavior**
User should be able to add events on commons other than HC.

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [x] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by mikethicke** [comment]
A bug in hc-simplesaml combined with some login weirdness was causing the user to not have the correct role for organizational commonses. Addressed by https://github.com/MESH-Research/humanities-commons/commit/77bc5f5e5016ac65efc5d906c709231ea58517f3
