### ISSUE TITLE
Updating MLA Commons site theme footer

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#667]
We received this email from Anatole. It looks like the footer is custom coded:

I'm emailing because I noticed that the footer on [governance.mla.hcommons.org](http://governance.mla.hcommons.org/) has "suite 500" as part of the MLA's address. I poked around to try to edit it, and when I couldn't, I asked Anne about it. She found that the footer is coded into the MLA Commons site theme footer widget on the MESH research [Github repository here](https://github.com/MESH-Research/cbox-mla-blog/blob/main/templates/parts/footer-widgets.php). I was wondering if it would be possible for the code to be updated to remove "suite 500" from the MLA's address.

**Comment by mikethicke** [comment]
Updated
