### ISSUE TITLE
MLA Commons shows "join group" buttons twice

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#690]
**Describe the bug**
On MLA Commons groups, the "join group" button is showing up twice for all groups. This is only affecting MLA Commons and not HCommons generally or the other member nodes. 

**To Reproduce**
1. Go to 'MLA Commons'
2. Click on 'Groups and Forums'
3. Scroll down to the list of groups. "Join Group" will appear twice next to each listed group. 

**Context**
Does this bug on production, development, or both?
- [ ] Tested on development instance
- [ ] Occurs on development instance
- [x] Tested on production
- [x] Occurs on productions

**Screenshots**
![Screenshot 2023-07-25 at 3.41.45 PM.png](https://images.zenhubusercontent.com/62572e0e3e1b973699e0382a/f1f2e825-1f73-4f60-8a38-e6cb65c5959b)

**Comment by mikethicke** [comment]
Doubled join button removed with temporary fix while plan for removing cbox-auth is developed.
