### ISSUE TITLE
Item pages serve ~MB of hidden, inaccessible page content

### ISSUE THREAD

**Issue by sneakers-the-rat** [mlaa/commons#692]
**Describe the bug**
The full HTML of an item page (like https://hcommons.org/deposits/item/hc:54749/ ) is 1.7MB, which is pretty big for a single page! 

Almost all of that size are the entries in the "browse by subject, browse by item" facets beneath the item content, but they are not actually visible on the page and as far as I can tell it's impossible to make them be - clicking on any of the links takes you to a different page.

When those are removed, the page itself is 91K (or ~5% of the size). I think y'all can save yourself a lot of bandwidth and make the page feel *a lot* snappier by not serving those invisible entries.

**Context**
Does this bug on production, development, or both?
- [ ] Tested on development instance
- [ ] Occurs on development instance
- [x] Tested on production
- [x] Occurs on productions

**Comment by mikethicke** [comment]
Thanks. And yes, you're right. The current repository application is being phased out, so this probably isn't something we're going to address though.
