### ISSUE TITLE
Add Footnotes Made Easy plugin to the Commons network

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#696]
A user contacted us about trying to use a footnotes plugin on an FSE theme, and the footnotes options we offer only work on Legacy themes. Add [Footnotes Made Easy](https://wordpress.org/plugins/footnotes-made-easy/) as an option for users--Bonnie has used it on other sites and feels it's a good option. 

Once it's added, I'll email the user to tell them it's installed.

**Comment by bjr70** [comment]
Can vouch for this one. It's open source, updated often, and easy to use. I use it both on HuMetrics and on the OER site.

**Comment by mikethicke** [comment]
Ok, seems reasonable.

**Comment by mikethicke** [comment]
Plugin is installed and made available to users on all networks.

**Comment by babaklar** [comment]
Emailed user.
