### ISSUE TITLE
regularize "username" to "user name" in translations where possible

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/commons#7]
For instance, on the login screen. See mlaa/cbox-auth#3 for a screenshot.

**Comment by chriszarate** [comment]
It's now in M-W Collegiate closed-up, so we've successfully waited this one out.

**Comment by kfitz** [comment]
Woo hoo!

**Comment by JonathanReeve** [comment]
So should we regularize "user name" to "username"?

**Comment by chriszarate** [comment]
Yes, in user-facing UI copy. We can leave it as-is in historical content like blog and forum posts.

**Comment by JonathanReeve** [comment]
Cool. Editing and reopening this issue to reflect that.

**Comment by chriszarate** [comment]
Thanks!

**Comment by JonathanReeve** [comment]
In internal trac ticket 4250 (related to issue mlaa/cbox-auth#3), Sara says Editorial consensus is that house style is sticking with "user name." So I suppose I'll change this back, unless there are opinions to the contrary.

**Comment by chriszarate** [comment]
Closing in favor or broader editorial review.
