### ISSUE TITLE
Move user's ASEEES site to HCommons site

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#708]
[A user](https://hcommons.org/members/katiabowers/) would like the content from [katherinebowers.aseees.hcommons.org](katherinebowers.aseees.hcommons.org) exported over to [katherinebowers.hcommons.org](katherinebowers.hcommons.org). Once the site has been moved, I'll let the user know.

**Comment by bjr70** [comment]
Hey @mikethicke any chance you can look at this one in the next week or so? It's been out here for a while.

**Comment by mikethicke** [comment]
The site is moved: https://katherinebowers.hcommons.org/

**Comment by babaklar** [comment]
Emailed user.
