### ISSUE TITLE
Discussion post accidentally hidden, cannot view or retrieve post

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#713]
**Describe the bug**
Julie Libarkin accidentally marked a discussion topic hidden. It shows on the page as "hidden" but when you click it does not show any content. I can't find anywhere on the backend to view discussion topics or to retrieve on that's been hidden. Help? 

Group: https://hcommons.org/groups/stem-ed-pacer-meet-the-mentors-835298035/?view=all

**Expected behavior**
I expect to be able to view the hidden topic as an admin.

**Context**
Does this bug on production, development, or both?
- [ ] Tested on development instance
- [ ] Occurs on development instance
- [ ] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by mikethicke** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmREIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--af2e9a526ca88dabc0deda767795e8a19078707d/image.png)

Looks like it was acutally set as pending, which is perhaps why you couldn't find it.

I approved it and it is back.
