### ISSUE TITLE
Private replies are being indexed by ElasticSearch and showing up in search results

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#728]
**Describe the bug**
From Kathleen: "Scott S just let me know that he'd searched MSU Commons for me (I'm assuming "Kathleen Fitzpatrick") and the first hit he got was a post by Garth Sabo. Weird in and of itself. I went to MSUC and ran the search and my profile came out on top, but I saw the post by Garth and clicked through... to a private group. Private group posts should not come up in search results unless you're a logged in member of the group, and I was not logged in."

From Mike: "You can't visit the group to read the full post, as it's a private group, but the post itself isn't private so it's getting indexed... kind of odd that private groups wouldn't set replies to private."

From Mike: "There actually is a line in our search plugin that attempts to address this issue: https://github.com/MESH-Research/elasticpress-buddypress/blob/8387ec4b1d20b31b7d5f0d159ca79009d8a0b2dc/elasticpress-rest.php#L197C8-L197C60 but it's not going to work because the parent of a reply is a topic, not the group itself."

There's three options: 
1. Stop indexing topics and replies so they don't show up in the search at all.
2. Stop the default elasticpress plugin from indexing topics and replies, and write a new function to do so that checks a group's status. This will exclude topics and replies in private groups from the search even to members of those groups. It's also going to take some work. The rewrite might speed up search though?
3. Do nothing---as far as I can tell this is how it's always worked. Not good obviously, but it's been like this for a long time.

Given that groups architecture and functionality will be updated in the next year, the decision was made to go with option 1. Re-indexing may need to happen overnight due to size. 

**Context**
Does this bug on production, development, or both?
- [ ] Tested on development instance
- [ ] Occurs on development instance
- [ ] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by mikethicke** [comment]
The fundamental issue is that topics and replies are stored by bbPress as WordPress posts but the BuddyPress groups containing them are not, and the public / private / hidden status of groups is not inherited by bbPress posts.

As an interim solution, we are removing topics and replies from indexing: https://github.com/MESH-Research/hc-custom/commit/1f2efaf1071ec149295a4697bcc19166b5ae46e3

**Comment by mikethicke** [comment]
Topics and replies are no longer being indexed.

Fix to above commit: https://github.com/MESH-Research/hc-custom/commit/819fc1119d0cb4a58563559a61a72aee6ba8b23a
