### ISSUE TITLE
Move site from HCommons to MSU Commons

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#734]
An [MSU student](https://registry.hcommons.org/registry/co_people/canvas/166031) created [a personal site](https://corinnemansour.hcommons.org/) under HCommons, and it should have been under MSU Commons. I added MSU Commons access to her account, and the site needs to be moved onto MSU Commons.

**Comment by bjr70** [comment]
Any news on this one?

**Comment by mikethicke** [comment]
The site is move: https://corinnemansour.commons.msu.edu/

**Comment by babaklar** [comment]
Emailed user.
