### ISSUE TITLE
Can someone pull stats for a group - downloads/views? 

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#737]
Can someone pull info or tell me where I could pull it? 

Group: https://hcommons.org/groups/regional-economic-innovation/

Thanks!

**Comment by mikethicke** [comment]
[eda_deposit_stats.csv.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGd1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3cc004bae720f02ad4b016072ec406a8b756c344/eda_deposit_stats.csv.zip)

**Comment by bjr70** [comment]
Sheet sent to user. Thanks!
