### ISSUE TITLE
Add "Translate WordPress – Google Language Translator" plugin to Commons sites

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#742]
## Overview

To add a plugin to the Commons, we want to ensure that it fulfills a need for our users that cannot be addressed with our currently available plugins and themes, that it works with our configuration, and that we can adequately test it. Once a plugin is being used, it becomes very difficult to remove without causing problems, so we want to be very careful about adding plugins that will increase our support burden and might cause problems along the way.

## Checklist

- [x] Make plugin request (see below)
- [ ] Initial evaluation (see below)
- [ ] Install plugin on dev / staging for testing
- [ ] Plugin works without issue?
- [ ] Add plugin to plugin catalogue
- [ ] Add necessary support documentation
- [ ] Create test script for plugin and add to plugin catalogue
- [ ] Install plugin on production
- [ ] Notify users, possible blog post

## Plugin Request Form

Plugin Name: Translate Wordpress - Google Language Translator
Plugin URL: [https://wordpress.org/plugins/google-language-translator/](https://wordpress.org/plugins/google-language-translator/)
Requesting User: Meredith Hale (ARLIS/NA)
Rationale: See description below from Meredith about adding this plugin to ARLIS/NA sites:

I've previously brought it to the attention of support staff that ARLIS/NA members would like to have a plugin for Wordpress sites to support translation. In particular, the Texas-Mexico Chapter and the MOQ (Montreal, Ottawa, Quebec) Chapter of ARLIS/NA would like their sites to be able to be translated to Spanish and French respectively. They previously had plugins on their old Wordpress sites prior to migration to the Commons and it is important to them to continue to make their sites accessible to all their members. Potentially the following plugin could meet those needs - [https://wordpress.org/plugins/google-language-translator/](https://wordpress.org/plugins/google-language-translator/)

## Initial Evaluation
Can the plugin's use case be (nearly) covered by existing functionality?
Is the plugin free and open source?
High active installations (wordpress.org)?
Is 'WP Hive Insights' (wordpress.org) all green?
Is plugin compatible with block editor?
Is the plugin superior to similar alternatives?

**Comment by babaklar** [comment]
More insight from Meredith on why ARLIS/NA is hoping we add the plugin to our network. This seems like a strong argument for adding the plugin, although perhaps other options within our network may also be considered. 

"I believe both chapters see the plugin as a way to increase the accessibility of their content. Given that Mexico and the province of Quebec have languages other than English as their official language, the chapters want to ensure that their members from outside of the US can access their web content. As ARLIS/NA’s name indicates, our Society is not confined to the United States and has membership across the North American continent. The plugin would be used to translate news posts, information on professional development opportunities, and other content present on their sites."

**Comment by babaklar** [comment]
Additional details she sent later:

A specific example of the kind of opportunity we want to make more accessible is the Lois Swan Jones Professional Development Award, a monetary award distributed yearly that goes toward conference expenses and a year of membership in the ARLIS/NA Texas-Mexico chapter. We are always trying to recruit more Mexico-based chapter members as well!

In case it’s helpful, here’s a link to the opportunity Helen mentioned on their HC website - https://texasmexico.arlisna.hcommons.org/lois-swan-jones-award/ Here’s also a link to the MOQ chapter site outside of the Commons - http://arlismoq.ca/home/. You can see that the entire site is offered in French and English.

**Comment by babaklar** [comment]
Meredith responded that a manual translator plugin will work for our team. Here is an additional note she added.

"Researching other plugins that address your security concerns makes a lot of sense. Please do begin that work. My only counter would be that finding options that are time efficient is important to our Society members. Many do this service work outside of their job. The Texas-Mexico chapter also shared that they sometimes use [Deepl](https://www.deepl.com/translator) This could be an additional service to look into assuming there is a plugin available."

**Comment by bjr70** [comment]
Another plugin added.
