### ISSUE TITLE
Deposits added to group are not appearing in the group

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#743]
A user contacted us about the ["Encoding Cultures" Joint MEC and TEI Conference group](https://hcommons.org/groups/encoding-cultures-joint-mec-and-tei-conference/deposits/) he created for a conference. Although users are able to add the group to the deposit, the deposits are not appearing in the group. 

Sample deposit (when you click on the name of the group, it goes to a blank page): [https://hcommons.org/deposits/item/hc:59549/](https://hcommons.org/deposits/item/hc:59549/ )

Bonnie and I suspect this could be from the quotation marks in the name of the group.

**Comment by mikethicke** [comment]
This was indeed an issue with the quotation marks.

A couple of changes were necessary:

stripping slashes from parameters before searching: https://github.com/MESH-Research/humcore/commit/9c049e15c079a76eed0542764c883b052433de92

converting smart quotes to simple quotes before searching: 

https://github.com/MESH-Research/humcore/commit/8a6255efe8f6ee76f91886b310b759a85bed325b

Search is working now on the group page and in CORE.

**Comment by babaklar** [comment]
Emailed user.
