### ISSUE TITLE
Uploads to group being marked as "awaiting moderation"

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#744]
Uploads to the [CLCS Global Hispanophone group](https://mla.hcommons.org/wp-admin/network/admin.php?page=bp-groups&gid=413&action=edit) by [Jo Xi Chen](https://mla.hcommons.org/wp/wp-admin/edit.php?post_status=bp_docs_pending&post_type=bp_doc) are being marked as "awaiting moderation." I've looked through settings and don't see anything popping out that would cause this. As a superadmin I also don't seem to have the ability to "approve" the uploads. Help? I feel like we've see this before.

**Comment by bjr70** [comment]
@mikethicke this user is still seeing all their docs go into moderation. I've looked at their profile but I can't see anything wrong with it. How else can we troubleshoot this?

**Comment by mikethicke** [comment]
I thought we were waiting on MLA to promote them to an admin for the group in their API... @bjr70 do you know if that's been done?

**Comment by bjr70** [comment]
No, I'll ask Anatole.

**Comment by bjr70** [comment]
No further issues reported. I think we're good.
