### ISSUE TITLE
Upgrade RDS

### ISSUE THREAD

**Issue by mikethicke** [mlaa/commons#758]

**Comment by tzouris** [comment]
Upgrade from db.m5.xlarge to db.m5.2xlarge.
Specs: 4 vCPUs, 416 GiB RAM --> 8 vCPUs, 32 GiB RAM
Monthly cost: $250 --> $500

**Comment by tzouris** [comment]
Upgrade time: 17 mins. Database went offline for about a minute about 4 minutes after the upgrade started.
