### ISSUE TITLE
User still appearing in search even though they've been deleted from the Commons

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#800]
A user contacted us because we deleted their account, but they are still able to see it when searching on the Commons. This only occurs when using the search bar in the top nav, not from the user page. Clicking on the profile link goes back to the Commons homepage. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5fe3debaaf38690d37b5dfb74d95729a6b3a50b2/Screenshot%202023-11-30%20at%201.16.07%20PM.png)

**Comment by mikethicke** [comment]
ElasticPress used to be configured to completely reindex nightly. I removed that functionality for performance reasons (it was taking several hours and sometimes longer). An unanticipated side effect of this is that deleted members were never cleaned up. I have re-instituted a weekly cron job to re-index. It should run on Saturdays. Will check back next Monday to confirm that the user no longer appears in search results.

**Comment by mikethicke** [comment]
After scheduled re-index, the user no longer appears in search results.

**Comment by babaklar** [comment]
Emailed user.
