### ISSUE TITLE
Dashboard testing - Cannot edit or add email address

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#823]
**Describe the bug**
I logged into the Commons as Joe Test (hctester0), clicked on Manage Account, and used the Google method to get to the dashboard. Once there I got the screenshot below--it's not showing any emails for the user and a red "error" banner. When trying to add an email address, nothing happens after choosing the "add" button. 

**To Reproduce**
1. Go to 'hcommons-dev.org'
2. Click on 'Manage Account'
3. Select Google login method

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [ ] Tested on production
- [ ] Occurs on productions

**Screenshots**
<img width="1326" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVpUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--874ef6d1dc69aee2d931b5e3365d08b6b453aad0/Screenshot%202023-12-12%20at%201.25.24%20PM.png" alt="Screenshot 2023-12-12 at 1.25.24 PM.png" />

**Additional context**

**Comment by mikethicke** [comment]
Based on initial testing, this affects regular users and not admins. There was a known issue about this previously at SCG, but it was apparently addressed. It's possible we either missed some commits or that we're hitting a case the fix didn't address. Arlen @ SCG is investigating.

**Comment by mikethicke** [comment]
This has been corrected by SCG.
