### ISSUE TITLE
SAH Commons "Member" page buttons are formatting incorrectly.

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#839]
**Describe the bug**
On SAH Commons, the "Members" page showed duplicate buttons. One is gray and cannot be selected. The other follows typical Commons styling. This only is affecting SAH Commons and not our other nodes. 

**To Reproduce**
1. Go to 'sah.hcommons.org/members'
2. Click on 'All Members' and 'SAH Members'
3. See error. 
4. Click on 'Following.' A similar bug occurs with slightly different text. 

**Expected behavior**
Only one button should occur. 

**Context**
Does this bug on production, development, or both?
- [ ] Tested on development instance
- [ ] Occurs on development instance
- [x] Tested on production
- [x] Occurs on productions

**Screenshots**
<img width="1700" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3puQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80affe9709dc6212c4697a8cf4d8a897be4fb841/Screenshot%202024-01-22%20at%209.31.21%E2%80%AFAM.png" alt="Screenshot 2024-01-22 at 9.31.21 AM.png" />

<img width="1684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzNuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ae9870e5cd413c46711ff2ce6c07adc503eca01/Screenshot%202024-01-22%20at%209.33.04%E2%80%AFAM.png" alt="Screenshot 2024-01-22 at 9.33.04 AM.png" />

**Comment by mikethicke** [comment]
This has been corrected.
