### ISSUE TITLE
Track metrics on profiles from Feb 19-March 22

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#845]
## Description ##
One of our community team students is doing a metrics project to track activity on the Commons. She is designing a "spring cleaning" campaign that will encourage users to update their digital presence on the Commons. During the week of March 4 - 8, she'll be posting about making changes, and she'll also run a special day during the week that will encourage users to make updates so their profiles are shared. 

## Deliverables ##
From February 19 to March 22, we're looking for data on:
- The last time users updated their profiles (prior to the beginning on the campaign on March 4)
- When users select the "edit" button on profiles
- When users select the "save changes" after making changes
- Character counts for changes on profiles (if this is possible)
- Amount of time spent editing a profile (if this is possible)

## Target Timeline ##
We'll start tracking on Feb 19 so there are two weeks before the campaign launches on social media. The campaign will last one week from March 4-8, and then we'll also track the two weeks after the campaign, wrapping up on March 22.

**Comment by mikethicke** [comment]
Script is located at `dev-scripts/commons/profile-updates.php`
