### ISSUE TITLE
Strange error on UP Commons site

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#861]
**Describe the bug**
From Brenna:

> I was trying to update a page in one of our UPC-hosted sites: [https://business.up.hcommons.org/data-statistics/sales-returns/](https://business.up.hcommons.org/data-statistics/sales-returns/)
> 
> Every time I try to Update/save the edits I have made, I get the following error message: "Updating failed. The response is not a valid JSON response." Screenshot attached.
> 
> I tried editing another page in the same site, and had success. (Which is good, as my test-edit page is actually the home of a very time-sensitive report I need to publish today—I had just noticed some nonsensical formatting on the problem page I thought to fix.)

**To Reproduce**
- Click on "edit page"
- Make a change in the block editor
- Try to update and publish
- Get error
- This only happens on this page! 

**Expected behavior**
Page should update

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [ ] Occurs on development instance
- [x] Tested on production
- [x] Occurs on productions

**Screenshots**

**Additional context**

**Comment by bjr70** [comment]
@mikethicke Larissa also experienced this issue on Wednesday here: https://sitetesting.commons.msu.edu/. She's gotten reports from four other users who are experiencing similar problems. 

<img width="1408" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNS9sQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc7f229f1cdabb901baeb8e60d4590f525be5c4b/Screenshot%202024-03-13%20at%2012.33.09%E2%80%AFPM%201.png" alt="Screenshot 2024-03-13 at 12.33.09 PM 1.png" />

**Comment by babaklar** [comment]
Another user has reported this now too on their site: [https://cantomensurable.hcommons.org/](https://cantomensurable.hcommons.org/). The user told us their other sites are not affected, and like above, the message reads "Updating failed. The response is not a valid JSON response."

**Comment by babaklar** [comment]
Another site: [https://calipfprogram.hcommons.org/](https://calipfprogram.hcommons.org/)

**Comment by bjr70** [comment]
Users reporting issue is fixed. No new reports.
