### ISSUE TITLE
Another JSON saving issue on MSU Commons

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#864]
**Describe the bug**
I thought we fixed this one but Kyle is still experiencing it. I was able to replicate it as well. 

**To Reproduce**
1. https://apexgrammateur.commons.msu.edu/
2. Try to save the post Ghosts in the Reservation as a draft. It does not save and the JSON error appears on screen and in the dev tools. 

MSU Commons dev not working. Can't test there. 

**Expected behavior**
The post should save with no error. 

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [ ] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by bjr70** [comment]
Images from user: 
<img width="1865" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXdYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c56174e28d7906f5f7aecd7f0bbf34f0f515d38/image001.png" alt="image001.png" />
<img width="819" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTRYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49b939e1eff021311637437efe4e59084d349687/image002.png" alt="image002.png" />

**Comment by mikethicke** [comment]
I'm guessing this was re-triggered by activating the translation plugin.

**Comment by bjr70** [comment]
Is it fixed?

**Comment by bjr70** [comment]
Solved
