### ISSUE TITLE
Files missing from an AUPresses group

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#874]
**Describe the bug**
https://up.hcommons.org/groups/digital-publishing-committee/documents/ on the production server the files show and are accessible. On the containerized version they are listed in the label but not visible. 

**To Reproduce**
1. Go to https://up.hcommons.org/groups/digital-publishing-committee/documents/ on the containerized version and click on "Files." It says there are 38. 
2. No files show

**Expected behavior**
Clicking on Files should show a list of the files and/or folders. 

**Context**
Does this bug on production, development, or both?
- [x] Tested on containerized instance
- [x] Occurs on containerized instance
- [x] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by mikethicke** [comment]
Addressed by:
- https://github.com/MESH-Research/knowledge-commons-wordpress/commit/90ab4b91344e1c469519c716ec2292a8d0b57b52
- https://github.com/MESH-Research/knowledge-commons-wordpress/commit/ab8755a3ab7fefae4ad20e413a3c93c3b7bf3b25
