### ISSUE TITLE
Reply by email not working for user in an MLA committee group

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#880]
A user emailed the below message, and a later follow up email reported that this started a few weeks ago. She's not receiving any error messages--her posts are not showing up and other users are not getting her messages. No one else in the group has reported the error.

"The email address for writing discussion threads for a committee I work with—[the Committee on Women, Gender, and Sexuality in the Profession](https://mla.hcommons.org/groups/committee-on-women-gender-and-sexuality-in-the-profession/)—has stopped working. Instead of writing directly from my email, I have to go to the Discussion area of the Commons group page to start a new discussion topic and to reply to messages. This is the address I write to:
group-committee-on-women-gender-and-sexuality-in-the-profession@reply.mla.hcommons.org"

**Comment by mikethicke** [comment]
This ended up being a AWS WAF issue. The rule allowing SparkPost webhook IPs was below the automatic AWS blocking rules in priority. Moving the AWS automatic rules to the bottom of the priority list addressed the issue.
