### ISSUE TITLE
Emails to reset password, password changed, etc have no site name for Knowledge Commons (possible BuddyPress issue?)

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#900]
A user just alerted me to the fact that "the emails to reset password, password changed, etc have no identifying information in them other than the domain of the sending email so they aren't immediately obvious that they are from KC." 

It looks like the emails pull "[{{{site.name}}}]" which I thought was "Site Title" but it appears not to be. I poked around to see if I could figure out where that was set, but I cannot. Can someone look at this?

**Comment by mikethicke** [comment]
This is an issue with PWM. Once we retire PWM this will be configurable in COmanage.
