### ISSUE TITLE
MLA groups broken 

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#901]
**Describe the bug**
I received a reply to my forum post and when I clicked to view the page was broken.

https://hcommons.org/groups/br-test-group-container-1/forum/topic/testing-3/?view=all#post-85095

This has been happening when on the forums, especially when there are attachments. 

**To Reproduce**
Click on this link: https://hcommons.org/groups/br-test-group-container-1/forum/topic/testing-3/?view=all#post-85095

If you view the thread from the main forum page it's fine, but when you click on a link in a reply it's broken. Happening in Firefox and Chrome. 

**Expected behavior**
The page should not be broken.

**Context**
Does this bug on production, development, or both?
- [x] Tested on development instance
- [x] Occurs on development instance
- [x] Tested on production
- [ ] Occurs on productions

**Screenshots**
<img width="1758" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ZjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8c6c72a3f5cd544aaaa721b66abf3819d310a8c/Page%20busted%20on%20forum.png" alt="Page busted on forum.png" />

**Additional context**

**Comment by bjr70** [comment]
On upload of an attachment the page is broken in the same way when it refreshes, as well.

**Comment by mikethicke** [comment]
Confirmed.

**Comment by mikethicke** [comment]
This issue exists on production as well:

<img width="1607" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEJjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65391b0e59b73a57239bbf102ee95d1971b6c220/Screenshot%202024-06-12%20at%206.54.13%E2%80%AFPM.png" alt="Screenshot 2024-06-12 at 6.54.13 PM.png" />

You can reproduce by viewing a discussion thread and clicking on any anchor link--ie. the grey #number link at the upper right of a post. It's not about attachments, but about having an anchor link in the URL. Will investigate the cause, but it is not particular to the containerization.

**Comment by bjr70** [comment]
Fixed
