### ISSUE TITLE
Can't delete user after move to containerized version launched

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#908]
**Describe the bug**
User spamming works, but when trying to delete a user a "There has been a critical error on this website" error is triggered in WordPress and the user is not deleted.

**To Reproduce**
1. Go to https://hcommons.org/wp-admin/network/users.php?orderby=id&order=desc and try to delete Rosie Test (hctester100@gmail.com)
2. Click on Delete
3. See error

**Expected behavior**

**Context**
Does this bug on production, development, or both?
- [ ] Tested on development instance
- [ ] Occurs on development instance
- [ ] Tested on production
- [ ] Occurs on productions

**Screenshots**

**Additional context**

**Comment by mikethicke** [comment]
Deleting users now fuctioning.
