### ISSUE TITLE
Issues with the AU Presses Board of Directors group

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#912]
We are experiencing an ongoing issue with the AU Presses Board of Directors managed group. This started a few weeks ago when Kate first reported that a handful of users who were added to the group were continually booted, and users who should not have been in the group were still able to access it. I was able to identify that I could fix the issue by resyncing their org identity in CoManage, which seems like it temporarily fixes the issue. However, even after resyncing multiple times, there are still ongoing issues with this in the group. 

I'm thinking this is probably a syncing issue between Salesforce and CoManage.

**Comment by babaklar** [comment]
Still experiencing this with a couple of the group members. Found this issue that seems like it could be related--not exactly the same issue, but similar components. [https://app.zenhub.com/workspaces/hc-development-61143609f268f000196abf18/issues/gh/mesh-research/commons/481](https://app.zenhub.com/workspaces/hc-development-61143609f268f000196abf18/issues/gh/mesh-research/commons/481)

**Comment by bjr70** [comment]
Was this resolved?

**Comment by bjr70** [comment]
Resolved.
