### ISSUE TITLE
Users receiving blank screen when accessing hcommons.org or attempting log in

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#915]
We've had numerous reports of users receiving a blank screen when they either access hcommons.org or go through the login process. We're having issues duplicating the errors, and there are not a lot of commonalities across the users. Reports have come from MSU Commons, ARLIS/NA Commons, and UP Commons. This happens across browsers and computers--even clearing cookies or using incognito doesn't seem to fix the error. 

I found this issue--it's not exactly what's happening, but some similar things here: https://app.zenhub.com/workspaces/hc-development-61143609f268f000196abf18/issues/gh/mesh-research/commons/398

I will continue to update this issue as I find out more info.

**Comment by bjr70** [comment]
Another user reports she's having an issue. This one is a UP user (jenniferkeegan@lsu.edu):

· What operating system are you using? I am using Microsoft Windows 10 Enterprise. However, I also tried to log into the site on my home computer, which runs Microsoft Windows 11 Pro.

· Are you using any browser plugins like Privacy Badger or Ghostery? No.

· Are you using an antivirus program with real-time monitoring of websites (Symantec and Norton have these features)? No, I am using Windows Defender exclusively.

· Is the error only happening on HCommons or also on other Commons nodes? I don’t have any other Commons nodes, so I’m not sure.

**Comment by bjr70** [comment]
We have another video. 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUxYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d4eacf4d55608f58079b68bfd9839bce4d5534e/UPCommonslogin_default.mp4)

**Comment by mikethicke** [comment]
I've traced the probable cause of this to a bug in the hc-notifications plugin, where a non-array was being treated as an array when a user was added to a group site. A hotfix is in place. We should consider removing this plugin entirely.
