### ISSUE TITLE
Some UP users are not able to post jobs to the AUPresses job site

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#916]
**Describe the bug**
Users are logged into AUPresses, but when they go to the jobs site it does not reflect that they're logged in. When they try to post a job it prevents them from accessing it. The reporting user: 

mmurphy@aupresses.org - https://registry.hcommons.org/registry/co_people/canvas/162535

**To Reproduce**

[See video.](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUxTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbc16aa599fa921c84d747c75fa39e0f70f63bb6/AUPresses%20Jobs%20-%20Google%20Chrome%202024-07-10%2015-15-41.mp4)

**Comment by mikethicke** [comment]
User's COmanage record and LDAP record look correct. They have a 'UP' badge on their profile. This looks like a bug, but further investigation is required. The next WP update will include logging for users who get this message.

**Comment by bjr70** [comment]
Yeah, Nora from AUPresses tried and got an error when trying to post a new job, but was able to get in to post: 

"Nora was using another employee's account. She is now registered with her own under her name but is getting error messages when trying to preview her post. 

 

"I was able to get back to the job posting page under my login, so at least that piece worked! As soon as I pushed the Preview button it gave me an error message and deleted it, so I guess I’ll try the actual posting piece again tomorrow!"

I'm trying to get the text of the error message.

**Comment by bjr70** [comment]
More information on the error: "When I click on preview after putting all of the info in, I get the below.  What’s odd is that when I did a test just before this error message, when I had only put a few random letters in the job description box it worked – so, I copied the full job description back in and then when I pushed preview again this is what I get."

<img width="1904" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekRZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5387689e301f673a611e5aaaab8d1b908c6910ff/unnamed.png" alt="unnamed.png" />

**Comment by bjr70** [comment]
The culprit was the "(TMS)" (no quotes) in the job listing. The theory is that WordPress choked on the "(TM." User has been able to post the listing. I'm closing this as it seems to be an odd occurrence. Will create another ticket if it continues.
