### ISSUE TITLE
Move AI Commons site from HCommons to MSU Commons

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#924]
Move content on [https://aicommons.hcommons.org/](https://aicommons.hcommons.org/) to [https://aicommons.commons.msu.edu/](https://aicommons.commons.msu.edu/). Existing content on the MSU Commons site linked here can be deleted. The MSU Commons user who created both sites is [freyesar](https://commons.msu.edu/members/freyesar/)

**Comment by mikethicke** [comment]
The site has been moved.

**Comment by babaklar** [comment]
Contacted user.
