### ISSUE TITLE
HASTAC latest post widget not updating with most recent

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#930]
Jackie Cahill reached out because the [HASTAC "latest posts" widget](https://hastac.hcommons.org/) is showing posts from 2022 and she can't get it to sort them from newest to oldest. We have had a [similar issue](https://app.zenhub.com/workspaces/hc-development-61143609f268f000196abf18/issues/gh/mesh-research/commons/732) with this before.

**Comment by mikethicke** [comment]
HASTAC uses the WP RSS Aggregator plugin to combine feeds from its sub sites into a single feed for display on the frontpage. WP RSS Aggregator is causing a fatal error because it uses a library that some other plugin is also using and doesn't check for that. I'm working on a fix.

**Comment by babaklar** [comment]
Fixed.
