### ISSUE TITLE
Renaissance Science and Medicine site displays "Stylesheet is missing" Wordpress error

### ISSUE THREAD

**Issue by babaklar** [mlaa/commons#935]
When trying to view the [Renaissance Science and Medicine site](https://renascimed.hcommons.org/), an error message reading "Stylesheet is missing" appears. The admin who reported the error can still view the site.

**Comment by mikethicke** [comment]
https://renascimed.hcommons.org/ has had Vantage Pro re-activated

**Comment by bjr70** [comment]
User notified.
