### ISSUE TITLE
MLA Group page link rerouting to hcommons.org

### ISSUE THREAD

**Issue by Hagen632** [mlaa/commons#968]
**Describe the bug**
When MLA users try to access the group "Commenting on Proposed Resolution 2025-1" they are rerouted back to the main hcommons.org page. 

**To Reproduce**
1. Go to the ['MLA Commons Groups and Forums' page](https://mla.hcommons.org/groups/?groups_search=Commenting+on+Proposed+Resolution+2025-1&groups_search_submit=Search)
2. Use the search tool to find the 'Commenting on Proposed Resolution 2025-1' group
3. See error

**Expected behavior**
Upon searching for the group in MLA Commons, the user is rerouted back to hcommons.org. It should just go to the specific group page so that it can be accessed. 

**Context**
Does this bug on production, development, or both?
- [ ] Tested on development instance
- [ ] Occurs on development instance
- [ ] Tested on production
- [ ] Occurs on productions

I was able to reproduce the error many times over a couple of days. 

**Screenshots**
I didn't attach any screenshots because the testing process explains it better. If you'd rather have them, let me know and I can add some. 

**Additional context**

**Comment by mikethicke** [comment]
It seems as though someone disabled / hid all of the group's components: Activity, Forum, Docs, etc. So there was no page that could be displayed for the group and it redirected to the homepage. I have enabled the Forum and Activity stream and made the default view Activity.

**Comment by Hagen632** [comment]
Awesome, thank you! I let them know.
